title: SoWatt's Blog
description: "Tek-naw-ledge-E and stuff"
author:
  name: "SoWatt"
  email: "someone@somewebsite.somedomain"
  url: "https://soWatt.github.io"
 
baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SoWatt"
year : "2020"
